## this file will difine the structure of dataset 
columns:
  age : int
  sex : category
  bmi : float
  children : int
  smoker : category
  region : category 
  expenses : float

numerical_columns:
  - age
  - bmi
  - children

categorical_columns:
  - sex
  - smoker
  - region

target_column:
  - expenses
  
## Becasue its a categorical dataset  Just to be Sure in Feature dataset will trainig
domain_value:
  sex:
    - female
    - male
  smoker:
    - yes
    - no
  region:
    - southwest
    - southeast
    - northwest
    - northeast